#tip 1: alias which in .bashrc is not support;
#tip 2:	can not add comments to shell cmd which in Makefile;
SHELL=/bin/bash

#**********************************************************************#

.PHONY: all clean #it is understood by make as not a file

all: ex1 ex3

CFLAGS=-Wall -g

clean:
	rm -f ex? ex1?
